<a href="https://colab.research.google.com/github/Marudhan/MiniProject/blob/main/MINI_PROJECT_6_AIRPORT_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Questions (Part I)**

1.Top 20 highest altitude airports in the world. Choose only “type” with “airport”
Output:
airport_id, name, city, country, altitude, rank

2.Top 20 countries that have the highest total # of airports.
Output:
country, total_airports, rank

3.Top 20 cities that have the highest total # of airports. (Two cities from different countries can have the same name, and you have to make sure the numbers are not messed up due to that!)
Output:
city, total_airports, rank

4.Pair of cities that have the same name, but from two different countries.
(hint: Use self join with query in Python (slack example))
Output:
city_a, country_a, city_b, country_b

In [1]:
import pandas as pd
from tabulate import tabulate
import traceback
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import numpy as py
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
db1 = pd.read_csv('/content/sample_data/airports.dat.txt', header=None, names=["Airport_ID","Name","City","Country","IATA","ICAO","Latitude","Longitude","Altitude","Timezone","DST","Tz database timezone","Type","Source"])
db1.head(5)

,Airport_ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database timezone,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports

In [3]:
db1_airport = db1[db1['Type'] == 'airport']
db1_airport_sorted = db1_airport.sort_values('Altitude', ascending=False)
top20_airports = db1_airport_sorted.head(20)
top20_airports = top20_airports[['Airport_ID', 'Name', 'City', 'Country', 'Altitude']]
top20_airports['rank'] = range(1, len(top20_airports) + 1)
print(tabulate(top20_airports, headers='keys', tablefmt='psql'))

+------+--------------+----------------------------------------+-------------+-----------+------------+--------+
|      |   Airport_ID | Name                                   | City        | Country   |   Altitude |   rank |
|------+--------------+----------------------------------------+-------------+-----------+------------+--------|
| 6542 |         9310 | Daocheng Yading Airport                | Daocheng    | China     |      14472 |      1 |
| 5028 |         6396 | Qamdo Bangda Airport                   | Bangda      | China     |      14219 |      2 |
| 6393 |         8921 | Kangding Airport                       | Kangding    | China     |      14042 |      3 |
| 5872 |         7932 | Ngari Gunsa Airport                    | Shiquanhe   | China     |      14022 |      4 |
| 2625 |         2762 | El Alto International Airport          | La Paz      | Bolivia   |      13355 |      5 |
| 2627 |         2764 | Capitan Nicolas Rojas Airport          | Potosi      | Bolivia   |      12913 |      6 |
| 5851 |         7894 | Yushu Batang Airport                   | Yushu       | China     |      12816 |      7 |
| 6420 |         8969 | Copacabana Airport                     | Copacabana  | Bolivia   |      12591 |      8 |
| 2654 |         2792 | Inca Manco Capac International Airport | Juliaca     | Peru      |      12552 |      9 |
| 7538 |        13483 | Golog Maqin Airport                    | Golog       | China     |      12426 |     10 |
| 5778 |         7766 | Syangboche Airport                     | Syangboche  | Nepal     |      12400 |     11 |
| 2626 |         2763 | Juan Mendoza Airport                   | Oruro       | Bolivia   |      12152 |     12 |
| 3874 |         4097 | Lhasa Gonggar Airport                  | Lhasa       | China     |      11713 |     13 |
| 6803 |        10943 | Hongyuan Airport                       | Ngawa       | China     |      11600 |     14 |
| 2342 |         2464 | La Quiaca Airport                      | Laboulaye   | Argentina |      11414 |     15 |
| 4040 |         4301 | Jiuzhai Huanglong Airport              | Jiuzhaigou  | China     |      11327 |     16 |
| 2649 |         2787 | Andahuaylas Airport                    | Andahuaylas | Peru      |      11300 |     17 |
| 5499 |         7313 | Uyuni Airport                          | Uyuni       | Bolivia   |      11136 |     18 |
| 2653 |         2791 | Francisco Carle Airport                | Jauja       | Peru      |      11034 |     19 |
| 3942 |         4174 | Manang Airport                         | Manang      | Nepal     |      11001 |     20 |
+------+--------------+----------------------------------------+-------------+-----------+------------+--------+

In [5]:
airport_counts = db1.groupby('Country')['Airport_ID'].count().sort_values(ascending=False).reset_index()
airport_counts = airport_counts.rename(columns={'Airport_ID': 'total_airports'})
airport_counts['rank'] = range(1, len(airport_counts) + 1)
top20_countries = airport_counts.head(20)
print(tabulate(top20_countries, headers='keys', tablefmt='psql'))

+----+----------------+------------------+--------+
|    | Country        |   total_airports |   rank |
|----+----------------+------------------+--------|
|  0 | United States  |             1512 |      1 |
|  1 | Canada         |              430 |      2 |
|  2 | Australia      |              334 |      3 |
|  3 | Russia         |              264 |      4 |
|  4 | Brazil         |              264 |      5 |
|  5 | Germany        |              249 |      6 |
|  6 | China          |              241 |      7 |
|  7 | France         |              217 |      8 |
|  8 | United Kingdom |              167 |      9 |
|  9 | India          |              148 |     10 |
| 10 | Indonesia      |              145 |     11 |
| 11 | Japan          |              123 |     12 |
| 12 | South Africa   |               99 |     13 |
| 13 | Argentina      |               96 |     14 |
| 14 | Mexico         |               84 |     15 |
| 15 | Italy          |               83 |     16 |
| 16 | Iran           |               82 |     17 |
| 17 | Sweden         |               77 |     18 |
| 18 | Turkey         |               76 |     19 |
| 19 | Colombia       |               75 |     20 |
+----+----------------+------------------+--------+